### ISSUE TITLE
AttributeError: 'Instance' object has no attribute 'set_default_value' on knitpy_overview.pymd building

### ISSUE THREAD

**Issue by nehalecky** [JanSchulz/knitpy#34]
Hi @JanSchulz, 

On building the example document, I hit one more error. I see that the document contains a few example errors, however, this one seems to originate from the initialization of the `ExecutionContent` class—and I suspect that also might be due to the great split to Jupyter. Interestingly, the documents are still generated (it seems correctly). Any thoughts?

Thanks! :)

```bash
[KnitpyApp] Converting examples/knitpy_overview.pymd...
[KnitpyApp] Changing to working dir: examples
[KnitpyApp] Converting document knitpy_overview.pymd to word_document
[KnitpyApp] Starting a new kernel: python
[KnitpyApp] Executed kernel startup lines for engine 'python'.
[KnitpyApp] Enabled image formats '[u'png', u'svg']' in engine 'python'.
[KnitpyApp] ERROR | Error while converting 'examples/knitpy_overview.pymd'
Traceback (most recent call last):
  File "/home/vagrant/miniconda-3.10.1/envs/energiscore-env/lib/python2.7/site-packages/knitpy/knitpyapp.py", line 220, in convert_documents
    outfilenames = kp.render(document_filename, output=self.export_format)
  File "/home/vagrant/miniconda-3.10.1/envs/energiscore-env/lib/python2.7/site-packages/knitpy/knitpy.py", line 685, in render
    self.convert(parsed, md_temp)
  File "/home/vagrant/miniconda-3.10.1/envs/energiscore-env/lib/python2.7/site-packages/knitpy/knitpy.py", line 205, in convert
    self._process_code(entry[1], context=context)
  File "/home/vagrant/miniconda-3.10.1/envs/energiscore-env/lib/python2.7/site-packages/knitpy/knitpy.py", line 312, in _process_code
    context.execution_finished()
  File "/home/vagrant/miniconda-3.10.1/envs/energiscore-env/lib/python2.7/site-packages/knitpy/knitpy.py", line 785, in execution_finished
    self.traits()[name].set_default_value(self)
AttributeError: 'Instance' object has no attribute 'set_default_value'
```

Any thoughts?

**Comment by JanSchulz** [comment]
As far as I read the code, the error occurs after all is written, so you see the generated docs (`execution_finished` "resets" the internal state to the default).

I suspect that the new 'traitlets' package does not use `set_default_value` anymore: https://github.com/ipython/traitlets/issues/106
